/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start login */
        get: operations["auth_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log out */
        get: operations["auth_logout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log out of all own sessions */
        get: operations["auth_logout_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return after Steam login */
        get: operations["auth_return"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get player rankings */
        get: operations["get_player_rankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the player that is currently logged in */
        get: operations["get_self"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get player by ID */
        get: operations["get_player"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rivals/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add rival */
        post: operations["add_rival"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rivals/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove rival */
        delete: operations["remove_rival"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rivals/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get own rivals and challengers */
        get: operations["get_own_rivals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search for scores */
        get: operations["get_scores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scores/rivals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get rivals' scores */
        get: operations["get_rival_scores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get score by ID */
        get: operations["get_score"];
        put?: never;
        post?: never;
        /** Delete score by ID */
        delete: operations["delete_score"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete shout by ID */
        delete: operations["delete_shout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/radio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get radio songs */
        get: operations["get_radio_songs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get global most played songs */
        get: operations["get_top_songs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get song by ID */
        get: operations["get_song"];
        put?: never;
        post?: never;
        /** Delete song by ID */
        delete: operations["delete_song"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{id}/extraInfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Manually update song extra info */
        put: operations["update_song_extra_info"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{id}/extraInfoByMbid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update song extra info by MBID */
        put: operations["update_song_extra_info_mbid"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get own permissions on song */
        get: operations["get_song_permissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{id}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get song's scores */
        get: operations["get_song_scores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{id}/shouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get song's shouts */
        get: operations["get_song_shouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get server stats */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int16
         * @enum {integer}
         */
        AccountType: 0 | 1 | 2;
        /** @description Wrapper for jwt crate's AuthBody because it doesn't implement ToSchema */
        AuthBodySchema: {
            access_token: string;
            token_type: string;
        };
        /**
         * Format: int16
         * @enum {integer}
         */
        Character: 0 | 1 | 2 | 3 | 4 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17;
        /**
         * @description Used for storing additional metadata from [MusicBrainz](https://musicbrainz.org).
         *     This lets us display fancy stuff™ on the song page.
         * @example {
         *       "aliasesArtist": null,
         *       "aliasesTitle": null,
         *       "coverUrl": "https://ia600309.us.archive.org/13/items/mbid-8a4b4cd1-917c-46bd-94eb-ab9f22a5c46f/mbid-8a4b4cd1-917c-46bd-94eb-ab9f22a5c46f-36122349406_thumb500.jpg",
         *       "coverUrlSmall": "https://ia600309.us.archive.org/13/items/mbid-8a4b4cd1-917c-46bd-94eb-ab9f22a5c46f/mbid-8a4b4cd1-917c-46bd-94eb-ab9f22a5c46f-36122349406_thumb.jpg",
         *       "id": 1,
         *       "mbid": "51517639-fafe-456a-9d6a-e4a11db00cf5",
         *       "mistagLock": false,
         *       "musicbrainzArtist": "Inverted Silence",
         *       "musicbrainzLength": 202559,
         *       "musicbrainzTitle": "Sendoff",
         *       "songId": 1,
         *       "updatedAt": "+002026-02-09T08:56:35.034878594Z"
         *     }
         * @example {
         *       "aliasesArtist": [
         *         "JamieP"
         *       ],
         *       "aliasesTitle": null,
         *       "coverUrl": "https://i.scdn.co/image/ab67616d0000b27356021e26fd463e7c1d062a9d",
         *       "coverUrlSmall": "https://i.scdn.co/image/ab67616d0000485156021e26fd463e7c1d062a9d",
         *       "id": 2,
         *       "mbid": "6c7e91a6-9cba-4ddf-b262-b5bf7be72d44",
         *       "mistagLock": false,
         *       "musicbrainzArtist": "Jamie Paige",
         *       "musicbrainzLength": 282315,
         *       "musicbrainzTitle": "Dyad",
         *       "songId": 2,
         *       "updatedAt": "+002026-02-09T08:56:35.034883403Z"
         *     }
         */
        ExtraSongInfo: {
            /** @description Alternative artist tags that can be matched to this song */
            aliasesArtist?: (string | null)[] | null;
            /** @description Alternative title tags that can be matched to this song */
            aliasesTitle?: (string | null)[] | null;
            coverUrl?: string | null;
            coverUrlSmall?: string | null;
            /** Format: int32 */
            id: number;
            mbid?: string | null;
            /**
             * @description For songs that have been mistagged by the automatic lookup.
             *     A value of `true` prevents any new metadata lookups by title
             */
            mistagLock: boolean;
            musicbrainzArtist?: string | null;
            /** Format: int32 */
            musicbrainzLength?: number | null;
            musicbrainzTitle?: string | null;
            /** Format: int32 */
            songId: number;
            /** Format: date-time */
            updatedAt: string;
        };
        FavoriteCharacter: {
            character: components["schemas"]["Character"];
            /** Format: int64 */
            timesUsed: number;
        };
        /**
         * Format: int16
         * @enum {integer}
         */
        League: 0 | 1 | 2;
        MbidRefreshBody: {
            recording_mbid: string;
            release_mbid?: string | null;
        };
        ModifyRivalRequest: {
            /** Format: int32 */
            rivalId: number;
        };
        /** @description Used for inserting additional metadata from [MusicBrainz](https://musicbrainz.org). */
        NewExtraSongInfo: {
            aliasesArtist?: string[] | null;
            aliasesTitle?: string[] | null;
            coverUrl?: string | null;
            coverUrlSmall?: string | null;
            mbid?: string | null;
            musicbrainzArtist?: string | null;
            /** Format: int32 */
            musicbrainzLength?: number | null;
            musicbrainzTitle?: string | null;
            /** Format: int32 */
            songId: number;
        };
        /**
         * @example {
         *       "accountType": 2,
         *       "avatarUrl": "https://avatars.akamai.steamstatic.com/fadb7d90654a38c196422ed308fc931f96440dde_full.jpg",
         *       "id": 1,
         *       "joinedAt": "+002023-05-23T18:56:24.000000000Z",
         *       "username": "m1nt_"
         *     }
         */
        PlayerPublic: {
            accountType: components["schemas"]["AccountType"];
            avatarUrl: string;
            /** Format: int32 */
            id: number;
            /** Format: date-time */
            joinedAt: string;
            username: string;
        };
        /**
         * @example {
         *       "results": [
         *         {
         *           "player": {
         *             "accountType": 2,
         *             "avatarUrl": "https://avatars.akamai.steamstatic.com/fadb7d90654a38c196422ed308fc931f96440dde_full.jpg",
         *             "id": 1,
         *             "joinedAt": "+002023-05-23T18:56:24.000000000Z",
         *             "username": "m1nt_"
         *           },
         *           "skillPoints": 4649
         *         }
         *       ],
         *       "total": 1
         *     }
         */
        PlayerRankingResponse: {
            results: components["schemas"]["PlayerWithRanking"][];
            /** Format: int64 */
            total: number;
        };
        /**
         * @example {
         *       "accountType": 2,
         *       "avatarUrl": "https://avatars.akamai.steamstatic.com/fadb7d90654a38c196422ed308fc931f96440dde_full.jpg",
         *       "id": 1,
         *       "joinedAt": "+002023-05-23T18:56:24.000000000Z",
         *       "stats": {
         *         "favoriteCharacter": {
         *           "character": 13,
         *           "timesUsed": 187
         *         },
         *         "rank": 1,
         *         "skillPoints": 4321,
         *         "totalPlays": 2008
         *       },
         *       "username": "m1nt_"
         *     }
         */
        PlayerResponse: components["schemas"]["PlayerPublic"] & {
            stats?: null | components["schemas"]["PlayerStats"];
        };
        /**
         * @example {
         *       "favoriteCharacter": {
         *         "character": 13,
         *         "timesUsed": 187
         *       },
         *       "rank": 1,
         *       "skillPoints": 4321,
         *       "totalPlays": 2008
         *     }
         */
        PlayerStats: {
            favoriteCharacter?: null | components["schemas"]["FavoriteCharacter"];
            /** Format: int32 */
            rank: number;
            /** Format: int32 */
            skillPoints: number;
            /** Format: int32 */
            totalPlays: number;
        };
        /**
         * @example {
         *       "player": {
         *         "accountType": 2,
         *         "avatarUrl": "https://avatars.akamai.steamstatic.com/fadb7d90654a38c196422ed308fc931f96440dde_full.jpg",
         *         "id": 1,
         *         "joinedAt": "+002023-05-23T18:56:24.000000000Z",
         *         "username": "m1nt_"
         *       },
         *       "skillPoints": 4649
         *     }
         */
        PlayerWithRanking: {
            player: components["schemas"]["PlayerPublic"];
            /** Format: int32 */
            skillPoints: number;
        };
        RadioSongResponse: {
            externalUrl: string;
            extraInfo?: null | components["schemas"]["ExtraSongInfo"];
            song: components["schemas"]["Song"];
        };
        RivalryResponse: {
            challengers: components["schemas"]["RivalryView"][];
            rivalries: components["schemas"]["RivalryView"][];
        };
        /**
         * @example {
         *       "establishedAt": "+002023-05-23T18:56:24.000000000Z",
         *       "rival": {
         *         "accountType": 2,
         *         "avatarUrl": "https://avatars.akamai.steamstatic.com/fadb7d90654a38c196422ed308fc931f96440dde_full.jpg",
         *         "id": 1,
         *         "joinedAt": "+002023-05-23T18:56:24.000000000Z",
         *         "username": "m1nt_"
         *       }
         *     }
         */
        RivalryView: {
            /** Format: date-time */
            establishedAt: string;
            rival: components["schemas"]["PlayerPublic"];
        };
        /**
         * @example {
         *       "density": 994,
         *       "feats": [
         *         "Ironmode",
         *         "Clean Finish",
         *         "Match21",
         *         "Butter Ninja",
         *         "Seeing Red"
         *       ],
         *       "goldThreshold": 84490,
         *       "id": 1,
         *       "isj": 0,
         *       "iss": 0,
         *       "league": 2,
         *       "playCount": 12,
         *       "playerId": 1,
         *       "score": 508143,
         *       "songId": 2,
         *       "songLength": 28224,
         *       "submittedAt": "+002026-02-09T08:56:35.034551699Z",
         *       "trackShape": [
         *         68,
         *         65,
         *         62,
         *         58,
         *         54,
         *         51,
         *         51,
         *         49,
         *         48,
         *         46,
         *         44,
         *         42,
         *         41,
         *         40,
         *         39,
         *         37,
         *         37,
         *         36,
         *         34,
         *         32,
         *         31,
         *         30,
         *         29,
         *         28,
         *         28,
         *         27,
         *         27,
         *         25,
         *         26,
         *         26,
         *         25,
         *         22,
         *         19,
         *         17,
         *         16,
         *         14,
         *         11,
         *         8,
         *         5,
         *         2,
         *         0,
         *         0,
         *         0,
         *         1,
         *         2,
         *         3,
         *         3,
         *         4,
         *         5,
         *         6,
         *         6,
         *         6,
         *         6,
         *         8,
         *         9,
         *         9,
         *         10,
         *         10,
         *         11,
         *         11,
         *         12,
         *         13,
         *         15,
         *         16,
         *         18,
         *         19,
         *         20,
         *         22,
         *         23,
         *         24,
         *         26,
         *         27,
         *         28,
         *         30,
         *         31,
         *         32,
         *         33,
         *         34,
         *         36,
         *         37,
         *         39,
         *         40,
         *         41,
         *         41,
         *         40,
         *         39,
         *         38,
         *         38,
         *         37,
         *         37,
         *         36,
         *         36,
         *         37,
         *         37,
         *         37,
         *         36,
         *         36,
         *         35,
         *         34,
         *         34,
         *         34,
         *         34,
         *         34,
         *         34,
         *         34,
         *         33,
         *         33,
         *         33,
         *         33,
         *         33,
         *         33,
         *         34,
         *         35,
         *         37,
         *         39,
         *         40,
         *         41,
         *         42,
         *         44,
         *         45,
         *         44,
         *         41,
         *         39,
         *         37,
         *         36,
         *         35,
         *         33,
         *         30,
         *         28,
         *         26,
         *         23,
         *         22,
         *         22,
         *         23,
         *         24,
         *         26,
         *         26,
         *         28,
         *         29,
         *         30,
         *         31,
         *         31,
         *         32,
         *         33,
         *         34,
         *         36,
         *         37,
         *         38,
         *         39,
         *         39,
         *         40,
         *         41,
         *         43,
         *         44,
         *         46,
         *         47,
         *         50,
         *         51,
         *         52,
         *         54,
         *         55,
         *         57,
         *         59,
         *         60,
         *         61,
         *         63,
         *         64,
         *         65,
         *         67,
         *         68,
         *         70,
         *         72,
         *         74,
         *         75,
         *         77,
         *         78,
         *         79,
         *         81,
         *         82,
         *         83,
         *         81,
         *         78,
         *         74,
         *         71,
         *         67,
         *         65,
         *         66,
         *         66,
         *         67,
         *         67,
         *         66,
         *         67,
         *         68,
         *         70,
         *         73,
         *         74,
         *         73,
         *         70,
         *         67,
         *         65,
         *         64,
         *         63,
         *         60,
         *         58,
         *         56,
         *         53,
         *         51,
         *         49,
         *         49,
         *         49,
         *         50,
         *         50,
         *         50,
         *         51,
         *         52,
         *         52,
         *         52,
         *         52,
         *         53,
         *         54,
         *         54,
         *         55,
         *         56,
         *         56,
         *         56,
         *         57,
         *         57,
         *         58,
         *         60,
         *         62,
         *         64,
         *         66,
         *         67,
         *         68,
         *         70,
         *         72,
         *         73,
         *         75,
         *         76,
         *         78,
         *         80,
         *         81,
         *         83,
         *         85,
         *         87,
         *         89,
         *         91,
         *         92,
         *         94,
         *         96,
         *         98,
         *         99,
         *         100,
         *         102,
         *         103,
         *         103
         *       ],
         *       "vehicle": 10,
         *       "xstats": [
         *         478,
         *         4,
         *         0,
         *         274,
         *         2,
         *         24612,
         *         136,
         *         21,
         *         9,
         *         21,
         *         1804,
         *         28,
         *         1,
         *         9,
         *         100,
         *         7,
         *         41,
         *         135,
         *         16,
         *         67,
         *         144,
         *         34,
         *         97,
         *         76,
         *         27,
         *         97,
         *         26,
         *         16,
         *         87,
         *         0,
         *         4,
         *         0,
         *         0
         *       ]
         *     }
         */
        Score: {
            /** Format: int32 */
            density: number;
            /** @description Bonuses like Clean Finish, Seeing Red, etc. */
            feats: (string | null)[];
            /** Format: int32 */
            goldThreshold: number;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            isj: number;
            /** Format: int32 */
            iss: number;
            league: components["schemas"]["League"];
            /** Format: int32 */
            playCount: number;
            /** Format: int32 */
            playerId: number;
            /** Format: int32 */
            score: number;
            /** Format: int32 */
            songId: number;
            /** Format: int32 */
            songLength: number;
            /** Format: date-time */
            submittedAt: string;
            trackShape: (number | null)[];
            vehicle: components["schemas"]["Character"];
            /** @description Extra data about the play with meaning depending on the character used, sent by the game as a string of x-seperated numbers */
            xstats: (number | null)[];
        };
        ScoreResponse: components["schemas"]["Score"] & {
            player?: null | components["schemas"]["PlayerPublic"];
        };
        ScoreSearchResponse: {
            results: components["schemas"]["ScoreSearchResult"][];
            /** Format: int64 */
            total: number;
        };
        ScoreSearchResult: components["schemas"]["Score"] & {
            extraInfo?: null | components["schemas"]["ExtraSongInfo"];
            player?: null | components["schemas"]["PlayerPublic"];
            song?: null | components["schemas"]["Song"];
        };
        /**
         * @example {
         *       "scoreCount": 13649,
         *       "searchSupported": true,
         *       "songCount": 15122,
         *       "userCount": 150
         *     }
         */
        ServerStats: {
            /** Format: int64 */
            scoreCount: number;
            searchSupported: boolean;
            /** Format: int64 */
            songCount: number;
            /** Format: int64 */
            userCount: number;
        };
        /** @description Route error with only an error message. */
        SimpleRouteErrorOutput: {
            error: string;
        };
        /**
         * @example {
         *       "artist": "inverted silence",
         *       "createdAt": "+002026-02-09T08:56:35.034856853Z",
         *       "id": 1,
         *       "modifiers": [
         *         "steep"
         *       ],
         *       "title": "sendoff",
         *       "updatedAt": "+002026-02-09T08:56:35.034857404Z"
         *     }
         * @example {
         *       "artist": "jamie paige",
         *       "createdAt": "+002026-02-09T08:56:35.034862894Z",
         *       "id": 2,
         *       "modifiers": [],
         *       "title": "dyad",
         *       "updatedAt": "+002026-02-09T08:56:35.034863115Z"
         *     }
         * @example {
         *       "artist": "reol",
         *       "createdAt": "+002016-03-18T20:37:42.000000000Z",
         *       "id": 3,
         *       "modifiers": [],
         *       "title": "no title",
         *       "updatedAt": "+002026-02-09T08:56:35.034866601Z"
         *     }
         */
        Song: {
            artist: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int32 */
            id: number;
            modifiers?: (string | null)[] | null;
            title: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SongResponse: components["schemas"]["Song"] & {
            extraInfo?: null | components["schemas"]["ExtraSongInfo"];
        };
        /**
         * @description General type used to specify sort order
         * @enum {string}
         */
        SortType: "asc" | "desc";
        TopSongResponse: {
            songData: components["schemas"]["SongResponse"];
            /** Format: int64 */
            timesPlayed: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Steam */
            308: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    auth_logout_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    auth_return: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthBodySchema"];
                };
            };
            /** @description OpenID verification failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_player_rankings: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRankingResponse"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_self: {
        parameters: {
            query?: {
                /** @description Include player's stats */
                withStats?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPublic"];
                };
            };
            /** @description Not logged in or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_player: {
        parameters: {
            query?: {
                /** @description Include player's stats */
                withStats?: boolean;
            };
            header?: never;
            path: {
                /** @description ID of player to get */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Player not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    add_rival: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModifyRivalRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RivalryView"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Couldn't find player to rival */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Rivalry already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    remove_rival: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModifyRivalRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Couldn't find player to un-rival or they aren't a rival */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_own_rivals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RivalryResponse"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_scores: {
        parameters: {
            query?: {
                /** @description Include player info */
                withPlayer?: boolean;
                /** @description Include song info */
                withSong?: boolean;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                pageSize?: number;
                /** @description Sort by submission time */
                timeSort?: components["schemas"]["SortType"];
                /** @description Sort by score */
                scoreSort?: components["schemas"]["SortType"];
                /** @description League to filter by */
                league?: components["schemas"]["League"];
                /** @description Character to filter by */
                character?: components["schemas"]["Character"];
                /** @description Player ID to filter by */
                playerId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreSearchResponse"];
                };
            };
            /** @description Song not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_rival_scores: {
        parameters: {
            query?: {
                /** @description Include player info */
                withPlayer?: boolean;
                /** @description Include song info */
                withSong?: boolean;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                pageSize?: number;
                /** @description Sort by submission time */
                timeSort?: components["schemas"]["SortType"];
                /** @description Sort by score */
                scoreSort?: components["schemas"]["SortType"];
                /** @description League to filter by */
                league?: components["schemas"]["League"];
                /** @description Character to filter by */
                character?: components["schemas"]["Character"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreSearchResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Song not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_score: {
        parameters: {
            query?: {
                /** @description Include player info */
                withPlayer?: boolean;
                /** @description Include song info */
                withSong?: boolean;
            };
            header?: never;
            path: {
                /** @description ID of score to get */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreSearchResult"];
                };
            };
            /** @description Score not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    delete_score: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of score to delete */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Score not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    delete_shout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of shout to delete */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Shout not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_radio_songs: {
        parameters: {
            query?: {
                /** @description Include extra info */
                withExtraInfo?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadioSongResponse"][];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_top_songs: {
        parameters: {
            query?: {
                /** @description Include extra info */
                withExtraInfo?: boolean;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopSongResponse"][];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_song: {
        parameters: {
            query: {
                /** @description Include extra info */
                withExtraInfo: boolean;
            };
            header?: never;
            path: {
                /** @description ID of song to get */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongResponse"];
                };
            };
            /** @description Song not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    delete_song: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of song to get */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No permission */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Song not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    update_song_extra_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of song to update */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewExtraSongInfo"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No permission */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Song not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    update_song_extra_info_mbid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of song to update */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MbidRefreshBody"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No permission */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Song not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_song_permissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of song */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongResponse"];
                };
            };
            /** @description Song not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_song_scores: {
        parameters: {
            query?: {
                /** @description Include player info */
                withPlayer?: boolean;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                pageSize?: number;
                /** @description League to filter by */
                league?: components["schemas"]["League"];
                /** @description Character to filter by */
                character?: components["schemas"]["Character"];
                /** @description Player ID to filter by */
                playerId?: number;
            };
            header?: never;
            path: {
                /** @description ID of song to get */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"][];
                };
            };
            /** @description Song not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    get_song_shouts: {
        parameters: {
            query: {
                /** @description Page number */
                page: number;
                /** @description Page size */
                pageSize: number;
            };
            header?: never;
            path: {
                /** @description ID of song to get */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongResponse"];
                };
            };
            /** @description Song not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStats"];
                };
            };
            /** @description Miscellaneous error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRouteErrorOutput"];
                };
            };
        };
    };
}
