export const characterList: string[] = [
	'Pointman Pro',
	'Double Vision Pro',
	'Vegas',
	'Pusher',
	'Eraser',
	'Invalid',
	'Invalid',
	'Invalid',
	'Invalid',
	'Double Vision',
	'Pointman Elite',
	'Mono Pro',
	'Eraser Elite',
	'Ninja Mono',
	'Double Vision Elite',
	'Pointman',
	'Pusher Elite',
	'Mono'
];
